### ISSUE TITLE
Undefined global variable

### ISSUE THREAD

**Issue by subhero24** [remorses/esbuild-plugins#12]
When using `@esbuild-plugings/node-modules-polyfill` as an ESBuild plugin, the output contains a reference to the `global` variable. When running the code in the browser it errors saying global is not defined.  It seems to come from the `process` polyfill. 

Is that polyfill mistakenly included? (as I used to have a Rollup build which also uses `rollup-plugin-node-polyfills` and did not include this polyfill in the build) or is there something missing that polyfills the `global` variable?

**Comment by raymclee** [comment]
same here using remix and deploy to cloudflare worker

**Comment by toranb** [comment]
same here - how can I help move this forward?

**Comment by toranb** [comment]
to workaround this for now I've added a banner js config that declares global as window and it appears to be working for the moment -if anyone can improve upon this please do :)
```
{
  bundle: true,
  target: 'es2017',
  banner: {js: 'if (!global) { var global = window; }'},
    plugins
}
```

**Comment by remorses** [comment]
Fixed in latest version 😀, thank you for the report

**Comment by toranb** [comment]
@remorses w/ node v14 I got this runtime error w/ esbuild 0.14.10 -w/ the prior version I did not get this runtime error

```
✘ [ERROR] panic: runtime error: index out of range [0] with length 0 (while parsing "node_modules/@esbuild-plugins/node-globals-polyfill/_virtual-process-polyfill_.js")

  debug.Stack (runtime/debug/stack.go:24)
  helpers.PrettyPrintedStack (internal/helpers/stack.go:9)
  bundler.parseFile.func1 (internal/bundler/bundler.go:179)
  panic (runtime/panic.go:1038)
  js_parser.Parse.func1 (internal/js_parser/js_parser.go:14530)
  panic (runtime/panic.go:1038)
  js_parser.newParser.func3 (internal/js_parser/js_parser.go:14510)
  api.validateDefines.func9 (pkg/api/api_impl.go:542)
  ```

**Comment by remorses** [comment]
It seems it was an esbuild issue defining a `{}` object for global, now global is defined using `globalThis`, which works on all platforms, try now

**Comment by toranb** [comment]
@remorses is this in a new version or did you somehow force push to v0.1.3 ?

**Comment by remorses** [comment]
it's `@esbuild-plugins/node-modules-polyfill@0.1.4`

**Comment by toranb** [comment]
@remorses perfect! Thanks again for the speedy work on this fix
