### ISSUE TITLE
Is it possible for node-resolve to ignore external paths

### ISSUE THREAD

**Issue by jpike88** [remorses/esbuild-plugins#13]
My code:

```
NodeResolvePlugin({
					extensions: ['.ts', '.js'],
					onResolved: (resolved) => {
						if (resolved.includes('node_modules')) {
							return {
								external: true,
							};
						}
						return resolved;
					},
				}),
```

It works well, when a bundle is made it won't include the node_modules libs in the bundle.

But what if I'm building without any node_modules libs present (like it's a CI runner that just wants to prepare the app bundle itself)? Can your plugin let me also ignore the resolution check completely so I don't get ```ERROR: Could not resolve``` errors in esbuild?

**Comment by remorses** [comment]
You can make a plugin that resolves everything that is not a relative path as external, you don’t need this plugin
