### ISSUE TITLE
[node-modules-polyfill] Replace unmaintained `rollup-plugin-node-polyfills` dependency

### ISSUE THREAD

**Issue by MichaelDeBoey** [remorses/esbuild-plugins#18]
Same reasoning as in https://github.com/ionic-team/rollup-plugin-node-polyfills/pull/32.

Since that repo is never touched in the last 3 years, it's probably a good idea to either look at the community forks (see https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/28) _or_ create our own fork.
I would prefer to use @FredKSchott [fork](https://github.com/FredKSchott/rollup-plugin-polyfill-node) as he's the creator of `snowpack` & that's the one used by the `snowpack` library too, so it probably has the most up to date version of the `rollup-plugin-node-polyfills` lib.

Edit: @FredKSchott's fork is also recommended by the @rollup team: https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency

**Comment by giuseppeg** [comment]
Related https://github.com/ionic-team/rollup-plugin-node-polyfills/issues/38

**Comment by MichaelDeBoey** [comment]
@vafanassieff #19 implements the fix

**Comment by vafanassieff** [comment]
Thanks ! I used an easier way for my use, i only needed `buffer`

See comment [here](https://github.com/vitejs/vite/issues/3817) and [here](https://github.com/vitejs/vite/discussions/2785)

**Comment by MichaelDeBoey** [comment]
@giuseppeg Is this fixed in @FredKSchott's `rollup-plugin-polyfill-node` fork?

@vafanassieff #19 implements the fix
