### ISSUE TITLE
Small typos in README

### ISSUE THREAD

**Issue by Niek** [remorses/esbuild-plugins#2]
`NodeModulesPolyfills` should be `NodeModulesPolyfillPlugin` in the README. Additionally, the `EsmExternals` import in the `node-globals-polyfill` plugin is a copy/paste error from the `esm-externals` plugin.

**Comment by remorses** [comment]
Thank you for reporting

default imports can have any name you want, it's not a typo 👍

Fixed the copy paste issue tho
