### ISSUE TITLE
error: Duplicate injected file "...@esbuild-plugins/node-globals-polyfill/_buffer.js"

### ISSUE THREAD

**Issue by plusminushalf** [remorses/esbuild-plugins#25]
I am trying to polyfill Node.js built-in modules, reference: https://medium.com/@ftaioli/using-node-js-builtin-modules-with-vite-6194737c2cd2

I am running into this problem: https://pastebin.com/GWRFqWVr
<img width="961" alt="image" src="https://user-images.githubusercontent.com/5251472/208454110-ffeffa69-488e-42e5-8207-1f0b2c819a54.png">

My Vite config file: https://gist.github.com/plusminushalf/33d3d8a45b2924c846348f3f0ace17d5

**Comment by remorses** [comment]
Fixed in latest version
