### ISSUE TITLE
Cannot read directory "\x00polyfill-node._stream_duplex": invalid argument

### ISSUE THREAD

**Issue by MichaelDeBoey** [remorses/esbuild-plugins#28]
When updating to v0.2.0 in the Remix repo (see https://github.com/remix-run/remix/pull/5274), we got the same error(s) as @connorjclark was talking about in https://github.com/remorses/esbuild-plugins/pull/19#discussion_r990506227:

> Cannot read directory "\x00polyfill-node._stream_duplex": invalid argument

https://github.com/remix-run/remix/actions/runs/4017689920/jobs/6902360260#step:7:122

I'm happy to create a PR if somebody could point me into the right direction 🙏

CC/ @remorses

**Comment by remorses** [comment]
Reverted to old polyfill lib

**Comment by MichaelDeBoey** [comment]
@remorses That means #18 should be re-opened I guess?

Opened #29 as a re-submission of #19
