### ISSUE TITLE
EventEmitter issue

### ISSUE THREAD

**Issue by Niek** [remorses/esbuild-plugins#3]
I'm seeing this issue on 2 separate projects that I'm converting to esbuild.

```js
const EventEmitter = require('events');

class Test extends EventEmitter {
  constructor() { };
  }
}
```
This will throw the runtime error: `Uncaught TypeError: Class extends value #<Object> is not a constructor or null` - it seems like the events module is not properly resolved to the `polyfills/events` module.

**Comment by remorses** [comment]
This is because esbuild wraps commonjs exports in objects to add getters, the following code works, use import instead of require

```ts
import EventEmitter from 'events';

class Test extends EventEmitter {
  constructor() { };
}
```

**Comment by Niek** [comment]
Using `import` is unfortunately not possible, as it's in a library that is compatible with older Node versions. Is there any other workaround?

**Comment by remorses** [comment]
Try accessing `EventEmitter` or `default` on that module, like

`const { EventEmitter } = require('events');`

**Comment by Niek** [comment]
Wow, that worked... I owe you a lot! Thanks! 😁
