### ISSUE TITLE
vite build: "ReferenceError: process is not defined"

### ISSUE THREAD

**Issue by tpluscode** [remorses/esbuild-plugins#30]
I have a simple app which builds and works fine in dev environment. For some dependencies I had to add `NodeGlobalsPolyfillPlugin({ process: true })`

I found that when I build and deploy the app, I'm getting `process is not defined` from the bundle...

**Comment by remorses** [comment]
that's because vite uses rollup for prod builds, you need to add a process polyfill for rollup too, in the top level plugins option

**Comment by tpluscode** [comment]
Gotcha, thanks for a lightning fast reply
