### ISSUE TITLE
assert is missing top-level function

### ISSUE THREAD

**Issue by m90** [remorses/esbuild-plugins#5]
I am trying to use this much-needed plugin to polyfill `assert` calls. Polyfiliing itself happens, however somehow the shape of the exported module does not match the `assert` api from the polyfill anymore.

In the default Node API, `require('assert')` is a function that you can call and that behaves like `assert.ok`: https://nodejs.org/dist/latest-v14.x/docs/api/assert.html#assert_assert_value_message

When bundling my code using esbuild and this plugin, the polyfilled `assert` module will look like this though:

```
  // @esbuild-plugins/node-modules-polyfill:assert
  var assert_exports = {};
  __export(assert_exports, {
    AssertionError: () => AssertionError,
    assert: () => ok,
    deepEqual: () => deepEqual,
    deepStrictEqual: () => deepStrictEqual,
    default: () => assert_default,
    doesNotThrow: () => doesNotThrow,
    equal: () => equal,
    fail: () => fail,
    ifError: () => ifError,
    notDeepEqual: () => notDeepEqual,
    notDeepStrictEqual: () => notDeepStrictEqual,
    notEqual: () => notEqual,
    notStrictEqual: () => notStrictEqual,
    ok: () => ok,
    strictEqual: () => strictEqual,
    throws: () => throws
  });
```

so any consumer that calls `require('assert')` will see an error of `assert is not a function`. I'm not entirely sure how this would actually work in a scenario that supports both ESM / CommonJS imports and if this is just me configuring esbuild incorrectly, but maybe you have some insights on what is going on here?

**Comment by remorses** [comment]
I think this is an esbuild limitation, to use the polyfills correctly you will need to use ESM imports instead of require

**Comment by m90** [comment]
In our setup assert is being required by a dependency of ours so we don't really have control over how modules are consumed. Does this mean such a scenario is not polyfillable using this approach?

**Comment by m90** [comment]
Let me know if I can help with anything (testing for example). Thank you!

**Comment by remorses** [comment]
Released in latest version, you can try and see if it works on your codebase

**Comment by m90** [comment]
Works fine for us now. Thanks for taking care of this so quickly.
