### ISSUE TITLE
Can you please create a new release for `node-globals-polyfill`

### ISSUE THREAD

**Issue by Octember** [remorses/esbuild-plugins#9]
Hi there,

I noticed in latest master of `node-globals-polyfill`, you changed `Buffer.js` with this commit: https://github.com/remorses/esbuild-plugins/commit/dcc1b37d22e19a541044734b3305aa6a18370d9f

But there is not a new release making use of it

Could you please create a new release? thank you

**Comment by remorses** [comment]
Released 0.1.1 now
